before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: pathman
    binary: pathman
    main: ./cmd/pathman
    goos:
      - windows
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

chocolatey:
  - name: pathman
    owners: YourName
    title: PathMan
    authors: YourName
    project_url: https://github.com/cumulus13/pathman
    license_url: https://github.com/cumulus13/pathman/blob/main/LICENSE
    project_source_url: https://github.com/cumulus13/pathman
    description: Professional Windows Environment Variable Manager
    icon_url: https://raw.githubusercontent.com/cumulus13/pathman/main/assets/icon.png